# Generated by Django 5.1.4 on 2024-12-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("model", models.CharField(max_length=200)),
                ("brand", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "factory_year",
                    models.IntegerField(
                        verbose_name=models.CharField(
                            blank=True, max_length=200, null=True
                        )
                    ),
                ),
                (
                    "model_year",
                    models.IntegerField(
                        verbose_name=models.CharField(
                            blank=True, max_length=200, null=True
                        )
                    ),
                ),
                (
                    "value",
                    models.FloatField(
                        verbose_name=models.CharField(
                            blank=True, max_length=200, null=True
                        )
                    ),
                ),
            ],
        ),
    ]
