# Generated by Django 5.1.4 on 2024-12-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_brand_alter_car_factory_year_alter_car_model_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="cars/"),
        ),
        migrations.AddField(
            model_name="car",
            name="plate",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
